package com.deanwagman.lumenmarsh.venueops.dashboard.domain;

public enum DashboardAttentionKind {
    CRITICAL_INCIDENT,
    MAJOR_INCIDENT,
    WEATHER_HAZARD,
    WEATHER_HOLD,
    OPEN_P1_WORK_ORDER,
    ABNORMAL_ATTRACTION,
    UNPUBLISHED_FLOW_RECOMMENDATION,
    UNASSIGNED_INCIDENT,
    UNACKNOWLEDGED_INCIDENT,
    ORPHAN_ADVISORY,
    STALE_DATA
}
