package com.deanwagman.lumenmarsh.venueops.maintenance.domain.event;

public enum MaintenanceEventType {
    MAINTENANCE_RECOMMENDATION_RECEIVED,
    MAINTENANCE_RECOMMENDATION_ACCEPTED,
    MAINTENANCE_RECOMMENDATION_DISMISSED,
    WORK_ORDER_CREATED,
    WORK_ORDER_OPENED,
    WORK_ORDER_ASSIGNED,
    WORK_ORDER_REASSIGNED,
    WORK_STARTED,
    CHECKLIST_RESULT_RECORDED,
    INSPECTION_REQUESTED,
    INSPECTION_REJECTED,
    INSPECTION_APPROVED,
    RESTORE_ESTIMATE_UPDATED,
    WORK_ORDER_READY_FOR_TESTING,
    WORK_ORDER_COMPLETED,
    WORK_ORDER_CANCELED,
    WORK_ORDER_INCIDENT_LINKED,
    NOTE_ADDED,
    EVIDENCE_ADDED
}
