import type { OperatorDashboard } from '@/features/dashboard/domain/dashboard';

export const calmDashboard: OperatorDashboard = {
  generatedAt: '2026-09-10T20:30:00Z',
  summary: {
    operatingAttractions: 1,
    attractionsNeedingAttention: 0,
    closedAttractions: 2,
    weatherHoldAttractions: 0,
    openIncidents: 0,
    majorOrCriticalIncidents: 0,
    pendingWeatherRecommendations: 0,
    publishedGuestAdvisories: 0,
    openP1WorkOrders: 0,
    unpublishedFlowRecommendations: 0,
  },
  needsAttention: [],
  openIncidents: [],
  attractionsNeedingAttention: [],
  pendingWeatherRecommendations: [],
  publishedGuestAdvisories: [],
  recentActivity: [],
  freshness: {
    venueOps: {
      status: 'LIVE',
      lastUpdatedAt: '2026-09-10T20:29:55Z',
    },
    environmentalData: {
      status: 'UNAVAILABLE',
      lastUpdatedAt: null,
    },
  },
};

export const stormDashboard: OperatorDashboard = {
  generatedAt: '2026-09-10T20:30:00Z',
  summary: {
    operatingAttractions: 2,
    attractionsNeedingAttention: 1,
    closedAttractions: 0,
    weatherHoldAttractions: 1,
    openIncidents: 3,
    majorOrCriticalIncidents: 2,
    pendingWeatherRecommendations: 1,
    publishedGuestAdvisories: 1,
    openP1WorkOrders: 1,
    unpublishedFlowRecommendations: 1,
  },
  needsAttention: [
    {
      kind: 'CRITICAL_INCIDENT',
      reason: 'Critical incident is open and needs a supervisor-led response.',
      href: '/incidents/inc-critical-1',
      subjectId: 'inc-critical-1',
      subjectLabel: 'Guest medical emergency',
      updatedAt: '2026-09-10T20:29:40Z',
    },
    {
      kind: 'MAJOR_INCIDENT',
      reason: 'Major incident is open.',
      href: '/incidents/inc-lightning-1',
      subjectId: 'inc-lightning-1',
      subjectLabel: 'Lightning near western basin',
      updatedAt: '2026-09-10T20:29:30Z',
    },
    {
      kind: 'WEATHER_HAZARD',
      reason: 'Pending warning-level weather recommendation: Place outdoor attractions on weather hold',
      href: '/attractions',
      subjectId: 'rec-lightning-1',
      subjectLabel: 'Lightning hold for outdoor attractions',
      updatedAt: '2026-09-10T20:28:00Z',
    },
    {
      kind: 'WEATHER_HOLD',
      reason: 'Cypress Coil is on weather hold.',
      href: '/attractions/cypress-coil',
      subjectId: 'cypress-coil',
      subjectLabel: 'Cypress Coil',
      updatedAt: '2026-09-10T20:29:10Z',
    },
    {
      kind: 'OPEN_P1_WORK_ORDER',
      reason: 'P1 work order LM-2026-0042 is open: Investigate elevated wheel vibration',
      href: '/maintenance/work-orders/6dbb04f2-b20d-4b16-ae57-43072fc2e408',
      subjectId: '6dbb04f2-b20d-4b16-ae57-43072fc2e408',
      subjectLabel: 'LM-2026-0042',
      updatedAt: '2026-09-10T20:28:30Z',
    },
    {
      kind: 'UNPUBLISHED_FLOW_RECOMMENDATION',
      reason: 'Unpublished flow recommendation: Redistribute from Mangrove Run',
      href: '/park-flow',
      subjectId: 'flow-rec-1',
      subjectLabel: 'Redistribute from Mangrove Run',
      updatedAt: '2026-09-10T20:28:10Z',
    },
    {
      kind: 'UNASSIGNED_INCIDENT',
      reason: 'Incident is open and unassigned.',
      href: '/incidents/inc-queue-1?assignment=unassigned',
      subjectId: 'inc-queue-1',
      subjectLabel: 'Queue overflow at Stormglass',
      updatedAt: '2026-09-10T20:27:00Z',
    },
  ],
  openIncidents: [
    {
      id: 'inc-critical-1',
      title: 'Guest medical emergency',
      severity: 'CRITICAL',
      status: 'ACKNOWLEDGED',
      assignedTo: 'Supervisor One',
      attractionIds: ['stormglass-station'],
      guestAdvisoryPublished: false,
      updatedAt: '2026-09-10T20:29:40Z',
      version: 2,
    },
    {
      id: 'inc-lightning-1',
      title: 'Lightning near western basin',
      severity: 'MAJOR',
      status: 'MITIGATING',
      assignedTo: 'Control Tower',
      attractionIds: ['mangrove-run', 'cypress-coil'],
      guestAdvisoryPublished: true,
      updatedAt: '2026-09-10T20:29:30Z',
      version: 4,
    },
    {
      id: 'inc-queue-1',
      title: 'Queue overflow at Stormglass',
      severity: 'MINOR',
      status: 'REPORTED',
      assignedTo: null,
      attractionIds: ['stormglass-station'],
      guestAdvisoryPublished: false,
      updatedAt: '2026-09-10T20:27:00Z',
      version: 1,
    },
  ],
  attractionsNeedingAttention: [
    {
      id: 'cypress-coil',
      name: 'Cypress Coil',
      area: 'Cypress Basin',
      status: 'WEATHER_HOLD',
      capacityMode: 'NOT_APPLICABLE',
      waitMinutes: null,
      statusMessage: 'Paused for weather.',
      updatedAt: '2026-09-10T20:29:10Z',
      relatedOpenIncidentCount: 1,
    },
  ],
  pendingWeatherRecommendations: [
    {
      id: 'rec-lightning-1',
      severity: 'WARNING',
      recommendedAction: 'Place outdoor attractions on weather hold',
      evidence: 'Simulated lightning strike near the western basin.',
      affectedAttractionIds: ['mangrove-run', 'cypress-coil'],
      operatorStatus: 'PENDING',
      linkedIncidentId: 'inc-lightning-1',
      observedAt: '2026-09-10T20:28:00Z',
      updatedAt: '2026-09-10T20:28:00Z',
      simulated: true,
    },
  ],
  publishedGuestAdvisories: [
    {
      id: 'inc-lightning-1',
      title: 'Weather conditions affecting outdoor attractions',
      message: 'Some outdoor attractions are temporarily paused.',
      severity: 'MAJOR',
      affectedAttractionIds: ['mangrove-run', 'cypress-coil'],
      updatedAt: '2026-09-10T20:29:20Z',
      incidentId: 'inc-lightning-1',
    },
  ],
  recentActivity: [
    {
      occurredAt: '2026-09-10T20:29:30Z',
      actor: 'operator@lumen-marsh.dev',
      domain: 'INCIDENT',
      action: 'MITIGATION_STARTED',
      subject: 'Lightning near western basin',
      reason: 'Lightning cell overhead',
      resultingVersion: 4,
      href: '/incidents/inc-lightning-1',
    },
    {
      occurredAt: '2026-09-10T20:29:20Z',
      actor: 'supervisor@lumen-marsh.dev',
      domain: 'INCIDENT',
      action: 'GUEST_ADVISORY_PUBLISHED',
      subject: 'Lightning near western basin',
      reason: null,
      resultingVersion: 3,
      href: '/incidents/inc-lightning-1',
    },
    {
      occurredAt: '2026-09-10T20:29:10Z',
      actor: 'operator@lumen-marsh.dev',
      domain: 'ATTRACTION',
      action: 'WEATHER_HOLD_PLACED',
      subject: 'Cypress Coil',
      reason: 'Lightning detected within operating radius',
      resultingVersion: 2,
      href: '/attractions/cypress-coil',
    },
  ],
  freshness: {
    venueOps: {
      status: 'LIVE',
      lastUpdatedAt: '2026-09-10T20:29:55Z',
    },
    environmentalData: {
      status: 'LIVE',
      lastUpdatedAt: '2026-09-10T20:28:00Z',
    },
  },
};
