package com.deanwagman.lumenmarsh.venueops.attraction.domain;

public enum AttractionEventType {
    ATTRACTION_TESTING_STARTED,
    ATTRACTION_TESTING_COMPLETED,
    ATTRACTION_OPENED,
    WEATHER_HOLD_PLACED,
    WEATHER_HOLD_CLEARED,
    TECHNICAL_FAULT_REPORTED,
    REPAIR_COMPLETED,
    ATTRACTION_CLOSED,
    CAPACITY_REDUCED,
    CAPACITY_RESTORED,
    WAIT_TIME_UPDATED
}
