import { describe, expect, it } from 'vitest';

import { stormDashboard } from '@/features/dashboard/test/fixtures';
import { formatShiftHandoff } from './handoff';

describe('formatShiftHandoff', () => {
  it('includes park status, attention, advisories, and data status', () => {
    const summary = formatShiftHandoff(stormDashboard, {
      generatedBy: 'operator@lumen-marsh.dev',
      connectionStatus: 'live',
      lastEventAt: Date.parse('2026-09-10T20:29:48Z'),
      now: new Date('2026-09-10T20:30:00Z'),
    });

    expect(summary).toContain('Lumen Marsh Shift Handoff');
    expect(summary).toContain('Generated by: operator@lumen-marsh.dev');
    expect(summary).toContain('2 attractions operating');
    expect(summary).toContain('1 attraction on weather hold');
    expect(summary).toContain('3 open incidents');
    expect(summary).toContain('2 major or critical incidents');
    expect(summary).toContain('Major incident: Lightning near western basin');
    expect(summary).toContain('Assigned to: Control Tower');
    expect(summary).toContain('Weather conditions affecting outdoor attractions');
    expect(summary).not.toContain('INTERNAL ONLY');
    expect(summary).toContain('VenueOps live connection healthy');
  });
});
