import type { StreamStatus } from '@/features/attractions/domain/streamHealth';
import { formatLabel } from '@/features/attractions/domain/formatters';
import { formatIncidentSeverity, formatIncidentStatus } from '@/features/incidents/domain/formatters';

import {
  attentionKindLabels,
  type OperatorDashboard,
} from './dashboard';
import { formatParkDateTime, formatSyncAge } from './parkTime';

export function formatShiftHandoff(
  dashboard: OperatorDashboard,
  options: {
    generatedBy: string;
    connectionStatus: StreamStatus;
    lastEventAt: number | null;
    now?: Date;
  },
): string {
  const generatedAt = options.now ?? new Date();
  const lines: string[] = [
    'Lumen Marsh Shift Handoff',
    `Generated: ${formatParkDateTime(generatedAt)}`,
    `Generated by: ${options.generatedBy}`,
    '',
    'Park status',
    ...parkStatusLines(dashboard),
    '',
    'Requires attention',
    ...attentionLines(dashboard),
    '',
    'Published guest advisories',
    ...advisoryLines(dashboard),
    '',
    'Pending weather recommendations',
    ...weatherLines(dashboard),
    '',
    'Recent important activity',
    ...activityLines(dashboard),
    '',
    'Data status',
    ...freshnessLines(dashboard, options),
  ];

  return lines.join('\n');
}

function parkStatusLines(dashboard: OperatorDashboard): string[] {
  const { summary } = dashboard;
  return [
    `- ${summary.operatingAttractions} ${plural(summary.operatingAttractions, 'attraction')} operating`,
    `- ${summary.attractionsNeedingAttention} ${plural(summary.attractionsNeedingAttention, 'attraction')} needing attention`,
    `- ${summary.closedAttractions} ${plural(summary.closedAttractions, 'attraction')} closed`,
    `- ${summary.weatherHoldAttractions} ${plural(summary.weatherHoldAttractions, 'attraction')} on weather hold`,
    `- ${summary.openIncidents} open ${plural(summary.openIncidents, 'incident')}`,
    `- ${summary.majorOrCriticalIncidents} major or critical ${plural(summary.majorOrCriticalIncidents, 'incident')}`,
    `- ${summary.pendingWeatherRecommendations} pending weather ${plural(summary.pendingWeatherRecommendations, 'recommendation')}`,
    `- ${summary.publishedGuestAdvisories} published guest ${plural(summary.publishedGuestAdvisories, 'advisory', 'advisories')}`,
  ];
}

function attentionLines(dashboard: OperatorDashboard): string[] {
  const criticalAndMajor = dashboard.openIncidents.filter(
    (incident) => incident.severity === 'CRITICAL' || incident.severity === 'MAJOR',
  );
  const unassigned = dashboard.openIncidents.filter((incident) => incident.assignedTo === null);
  const lines: string[] = [];

  if (dashboard.needsAttention.length === 0) {
    lines.push('- No items currently require attention.');
  }

  for (const incident of criticalAndMajor) {
    lines.push(`- ${formatIncidentSeverity(incident.severity)} incident: ${incident.title}`);
    lines.push(`  Status: ${formatIncidentStatus(incident.status)}`);
    lines.push(`  Assigned to: ${incident.assignedTo ?? 'Unassigned'}`);
    if (incident.attractionIds.length > 0) {
      lines.push(`  Affected: ${incident.attractionIds.join(', ')}`);
    }
  }

  for (const incident of unassigned) {
    if (incident.severity === 'CRITICAL' || incident.severity === 'MAJOR') {
      continue;
    }
    lines.push(`- Unassigned incident: ${incident.title}`);
  }

  for (const attraction of dashboard.attractionsNeedingAttention) {
    lines.push(
      `- Attraction not operating normally: ${attraction.name} (${formatLabel(attraction.status)})`,
    );
  }

  for (const item of dashboard.needsAttention) {
    if (item.kind === 'STALE_DATA' || item.kind === 'ORPHAN_ADVISORY') {
      lines.push(`- ${attentionKindLabels[item.kind]}: ${item.reason}`);
    }
  }

  return lines.length > 0 ? lines : ['- No items currently require attention.'];
}

function advisoryLines(dashboard: OperatorDashboard): string[] {
  if (dashboard.publishedGuestAdvisories.length === 0) {
    return ['- None published'];
  }
  return dashboard.publishedGuestAdvisories.map((advisory) => `- ${advisory.title}`);
}

function weatherLines(dashboard: OperatorDashboard): string[] {
  if (dashboard.pendingWeatherRecommendations.length === 0) {
    return ['- None pending'];
  }
  return dashboard.pendingWeatherRecommendations.map((recommendation) => {
    const simulated = recommendation.simulated ? ' (simulated)' : '';
    return `- ${formatLabel(recommendation.severity)}: ${recommendation.recommendedAction}${simulated}`;
  });
}

function activityLines(dashboard: OperatorDashboard): string[] {
  const recent = dashboard.recentActivity.slice(0, 8);
  if (recent.length === 0) {
    return ['- None recorded in this snapshot'];
  }
  return recent.map((event) => {
    const reason = event.reason ? ` (${event.reason})` : '';
    return `- ${formatParkDateTime(event.occurredAt)} · ${event.actor} · ${formatLabel(event.action)} · ${event.subject}${reason}`;
  });
}

function freshnessLines(
  dashboard: OperatorDashboard,
  options: { connectionStatus: StreamStatus; lastEventAt: number | null },
): string[] {
  const lines: string[] = [];
  if (options.connectionStatus === 'live') {
    lines.push('- VenueOps live connection healthy');
  } else if (options.connectionStatus === 'reconnecting') {
    lines.push('- Live updates interrupted. Reconnecting…');
  } else if (options.connectionStatus === 'stale') {
    lines.push('- Some operational information may be out of date.');
  } else {
    lines.push('- Live connection is still opening.');
  }

  const lastEventIso = options.lastEventAt ? new Date(options.lastEventAt).toISOString() : null;
  const age = formatSyncAge(lastEventIso ?? dashboard.freshness.venueOps.lastUpdatedAt);
  if (age) {
    lines.push(`- ${age.replace(/\.$/, '')}`);
  }

  lines.push(`- VenueOps data: ${dashboard.freshness.venueOps.status}`);
  lines.push(`- Environmental data: ${dashboard.freshness.environmentalData.status}`);
  return lines;
}

function plural(count: number, singular: string, pluralForm = `${singular}s`): string {
  return count === 1 ? singular : pluralForm;
}
